version: '3'
services:
  iped:
    build:
      context: .
      args:
        GITLAB_IP: ${GITLAB_IP-GITLAB_IP_NOT_SET}
    user: $UID
    working_dir: $PWD
    volumes:
      - ./:$PWD
      - /tmp/:${TMP-/tmp/}
      - /tmp/.X11-unix/:/tmp/.X11-unix/
    environment:
      - HTTP_PROXY
      - DISPLAY
      - GDK_BACKEND
      - IMAGE=${IMAGE-IMAGE}
      - OUTPUT=${OUTPUT-IPED}
      - Xmx=${Xmx-100G}
    command: bash -xc 'java -Djava.awt.headless=true -Xmx$Xmx -jar /iped/iped.jar -d $IMAGE -o $OUTPUT --nologfile --nogui --portable'
